### ISSUE TITLE
Add first class support for connecting to AlloyDB in Spring Boot

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/alloydb-java-connector#151]
### Feature Description

Cloud SQL Java Connector is wrapped in a Spring Boot starter artifact. This is for shipping something similar for AlloyDB.

**Comment by enocom** [comment]
Here's a write-up of how to use the Cloud SQL Spring Boot setup: https://spring-gcp.saturnism.me/app-dev/cloud-services/databases/cloud-sql

**Comment by ttosta-google** [comment]
PR https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2787 is under review.

**Comment by ttosta-google** [comment]
Closing this ticket as the PR https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2788 was merged.

Our customers will have access to it once [com.google.cloud:spring-cloud-gcp-dependencies](https://mvnrepository.com/artifact/com.google.cloud/spring-cloud-gcp-dependencies) `v5.1.3` is released.

**Comment by enocom** [comment]
Awesome! :clap:
