### ISSUE TITLE
GA release

### ISSUE THREAD

**Issue by tsingh2k15** [GoogleCloudPlatform/alloydb-java-connector#343]
### Question

Is it feasible for you to share some timelines around when this can come out of preview mode? I know until then, I can use auth-proxy as alternative. Please share if there are other alternatives I may explore for Java, Spring Boot and C# .NET applications.

**Comment by jackwotherspoon** [comment]
Cross-pollinating from https://github.com/GoogleCloudPlatform/alloydb-python-connector/issues/181
on the topic of C# 😄 
>  You may also find [this blog](https://esg.dev/posts/using-gcp-iam-with-pgsql/) interesting and worth a read, it explains how you can still leverage [automatic IAM authentication](https://cloud.google.com/alloydb/docs/manage-iam-authn) even without needing a Connector or Proxy for C#. We will be adding a sample similar to it into our official docs soon. It was written for Cloud SQL but the same can be done for AlloyDB.

**Comment by ttosta-google** [comment]
The Java Connector has officially achieved General Availability (GA) status.

@tsingh2k15 FYI
