### ISSUE TITLE
Update Maven Artifact Names and Descriptions

### ISSUE THREAD

**Issue by ttosta-google** [GoogleCloudPlatform/alloydb-java-connector#441]
We should update all maven artifacts to follow better naming conventions and to have better descriptions.

Maven artifacts: [alloydb-jdbc-connector](https://mvnrepository.com/artifact/com.google.cloud/alloydb-jdbc-connector), [alloydb-connector-parent](https://mvnrepository.com/artifact/com.google.cloud/alloydb-connector-parent)

Related to https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/1728

**Comment by enocom** [comment]
As discussed, we won't be renaming AlloyDB since it's a postgres-only database.
